[build]
  base = "packages/apps/vanilla-apps/newbie-challenge01-stack01/"
  publish = "packages/apps/vanilla-apps/newbie-challenge01-stack01/build-output/"
  command = "echo 'default context'"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
